_templates:
  common: &common
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: -1
          limit: 10
        - exit_status: "*"
          limit: 2
  benchmarks: &benchmarks
    timeout_in_minutes: 120
    retry:
      automatic: false
    soft_fail: true
    if: build.branch == "master"
    env:
      # BENCHMARKS_OFFICIAL is set from hooks/pre-command, based
      # on whether this is executing on the master branch.
      BENCHMARKS_DATASET: buildkite
      BENCHMARKS_PROJECT: gvisor-benchmarks
      BENCHMARKS_TABLE: benchmarks
      BENCHMARKS_UPLOAD: true
    agents:
      arch: "arm64"
      kvm: "true"
  netstack_test: &netstack_test
    env:
      PACKAGES: >
        ./pkg/tcpip
        ./pkg/tcpip/adapters/gonet
        ./pkg/tcpip/buffer
        ./pkg/tcpip/header
        ./pkg/tcpip/link/channel
        ./pkg/tcpip/network/ipv4
        ./pkg/tcpip/network/ipv6
        ./pkg/tcpip/stack
        ./pkg/tcpip/transport/icmp
        ./pkg/tcpip/transport/tcp
        ./pkg/tcpip/transport/udp
        ./pkg/waiter
env:
  # Force a clean checkout every time to avoid reuse of files between runs.
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - <<: *common
    label: ":docker: Containerd 1.4.3 tests (amd)"
    command: make containerd-test-1.4.3
    agents:
      arch: "amd64"
      os: "ubuntu"
  - <<: *common
    label: ":docker: Containerd 1.4.3 tests"
    command: make containerd-test-1.4.3
    agents:
      arch: "arm64"
      os: "ubuntu"
  - <<: *common
    label: ":docker: Containerd 1.5.4 tests (cgroupv2)"
    command: make containerd-test-1.5.4
    agents:
      cgroup: "v2"
      arch: "arm64"
      os: "ubuntu"
  - <<: *common
    label: ":docker: Containerd 1.6.0-rc.4 tests (cgroupv2)"
    command: make containerd-test-1.6.0-rc.4
    agents:
      cgroup: "v2"
      arch: "arm64"
      os: "ubuntu"

  # Networking tests.
  - <<: *common
    label: ":table_tennis_paddle_and_ball: IPTables tests"
    command: make iptables-tests
    agents:
      os: "ubuntu"
      arch: "arm64"
  - <<: *common
    label: ":construction_worker: Packetdrill tests"
    command: make packetdrill-tests
    agents:
      os: "ubuntu"
      arch: "arm64"
  - <<: *common
    label: ":hammer: Packetimpact tests"
    command: make packetimpact-tests
    agents:
      os: "ubuntu"
      arch: "arm64"
